/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    faqcategories: Faqcategory;
    faqs: Faq;
    'blog-posts': BlogPost;
    'page-configs': PageConfig;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    faqcategories: FaqcategoriesSelect<false> | FaqcategoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'page-configs': PageConfigsSelect<false> | PageConfigsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gestisci le categorie principali delle FAQ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqcategories".
 */
export interface Faqcategory {
  id: string;
  title: string;
  /**
   * Identificativo univoco (es. prenotazioni)
   */
  slug?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci le domande frequenti del sito.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  /**
   * Identificativo univoco per la URL (generato automaticamente)
   */
  slug?: string | null;
  answer: string;
  /**
   * Associa questa FAQ a una categoria
   */
  category?: (string | null) | Faqcategory;
  /**
   * Numero per ordinare le FAQ (1 = prima). Lascia vuoto per non ordinare.
   */
  order?: number | null;
  /**
   * Deseleziona per nascondere questa FAQ dal sito.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci gli articoli del blog. Scrivi il testo qui sotto e configura l'anteprima in fondo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * Identificativo univoco per la URL (es. noleggio-business).
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  /**
   * Scrivi qui il corpo del tuo articolo.
   */
  content: string;
  cardImage: string | Media;
  kicker?: string | null;
  excerpt?: string | null;
  ctaLabel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci i testi statici e le immagini delle varie pagine. Lascia i campi vuoti per utilizzare i testi di default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-configs".
 */
export interface PageConfig {
  id: string;
  slug: 'home' | 'noleggio-auto' | 'noleggio-premium' | 'noleggio-furgoni' | 'noleggio-elettriche' | 'scopri' | 'blog';
  hero?: {
    title?: string | null;
    description?: string | null;
    bgImage?: (string | null) | Media;
  };
  homeConfig?: {
    offersSection?: {
      title?: string | null;
      vantaggiTitle?: string | null;
      vantaggiSubtitle?: string | null;
      vantaggiBody?: string | null;
      imageVantaggi?: (string | null) | Media;
      vantaggiList?:
        | {
            testo?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    fleetSection?: {
      title?: string | null;
      subtitle?: string | null;
    };
    benefitsSection?: {
      title?: string | null;
      subtitle?: string | null;
      bgImage?: (string | null) | Media;
    };
    discoverSection?: {
      title?: string | null;
    };
  };
  autoConfig?: {
    rentalFeatures?: {
      title?: string | null;
    };
    comeFunziona?: {
      title?: string | null;
      subtitle?: string | null;
    };
    infoNoleggio?: {
      title?: string | null;
      subtitle?: string | null;
      body?: string | null;
      image?: (string | null) | Media;
    };
  };
  premiumConfig?: {
    premiumIntro?: {
      title?: string | null;
      subtitle?: string | null;
      image?: (string | null) | Media;
    };
    comeFunziona?: {
      title?: string | null;
      subtitle?: string | null;
    };
    modelChoice?: {
      title?: string | null;
      ctaLabel?: string | null;
    };
  };
  furgoniConfig?: {
    introFurgoni?: {
      title?: string | null;
      subtitle?: string | null;
      body?: string | null;
    };
    promo1?: {
      title?: string | null;
      body?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
      image?: (string | null) | Media;
    };
    promo2?: {
      title?: string | null;
      body?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
      image?: (string | null) | Media;
    };
    promo3?: {
      title?: string | null;
      body?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
      image?: (string | null) | Media;
    };
    wideBanner?: {
      image?: (string | null) | Media;
    };
    comeFunziona?: {
      title?: string | null;
      subtitle?: string | null;
    };
  };
  elettricheConfig?: {
    introElettrico?: {
      title?: string | null;
      subtitle?: string | null;
      body?: string | null;
      image?: (string | null) | Media;
    };
    vantaggiElettrico?: {
      title?: string | null;
      subtitle?: string | null;
    };
    comeFunziona?: {
      title?: string | null;
      subtitle?: string | null;
    };
  };
  scopriConfig?: {
    chiSiamo?: {
      title?: string | null;
      body?: string | null;
      image?: (string | null) | Media;
    };
    doveSiamo?: {
      title?: string | null;
      subtitle?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'faqcategories';
        value: string | Faqcategory;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'page-configs';
        value: string | PageConfig;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqcategories_select".
 */
export interface FaqcategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  answer?: T;
  category?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  content?: T;
  cardImage?: T;
  kicker?: T;
  excerpt?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-configs_select".
 */
export interface PageConfigsSelect<T extends boolean = true> {
  slug?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        bgImage?: T;
      };
  homeConfig?:
    | T
    | {
        offersSection?:
          | T
          | {
              title?: T;
              vantaggiTitle?: T;
              vantaggiSubtitle?: T;
              vantaggiBody?: T;
              imageVantaggi?: T;
              vantaggiList?:
                | T
                | {
                    testo?: T;
                    id?: T;
                  };
            };
        fleetSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        benefitsSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              bgImage?: T;
            };
        discoverSection?:
          | T
          | {
              title?: T;
            };
      };
  autoConfig?:
    | T
    | {
        rentalFeatures?:
          | T
          | {
              title?: T;
            };
        comeFunziona?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        infoNoleggio?:
          | T
          | {
              title?: T;
              subtitle?: T;
              body?: T;
              image?: T;
            };
      };
  premiumConfig?:
    | T
    | {
        premiumIntro?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
            };
        comeFunziona?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        modelChoice?:
          | T
          | {
              title?: T;
              ctaLabel?: T;
            };
      };
  furgoniConfig?:
    | T
    | {
        introFurgoni?:
          | T
          | {
              title?: T;
              subtitle?: T;
              body?: T;
            };
        promo1?:
          | T
          | {
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
            };
        promo2?:
          | T
          | {
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
            };
        promo3?:
          | T
          | {
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
            };
        wideBanner?:
          | T
          | {
              image?: T;
            };
        comeFunziona?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  elettricheConfig?:
    | T
    | {
        introElettrico?:
          | T
          | {
              title?: T;
              subtitle?: T;
              body?: T;
              image?: T;
            };
        vantaggiElettrico?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        comeFunziona?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  scopriConfig?:
    | T
    | {
        chiSiamo?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
            };
        doveSiamo?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}